import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import { TanStackQueryProvider } from "./provider/tanstack-query";
import { ReactQueryClientProvider } from "@/context/ReactQueryClientProvider";

import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

const Satoshi = localFont({
  src: "../../public/fonts/Satoshi-Medium.otf",
  variable: "--font-satoshi",
});

const Millik = localFont({
  src: "../../public/fonts/Millik.ttf",
  variable: "--font-millik",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body
          className={cn(
            inter.className,
            Satoshi.variable,
            Millik.variable,
            "antialiased min-h-screen"
          )}
        >
          <TanStackQueryProvider>{children}</TanStackQueryProvider>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
